# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sitar/laborki_git/cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sitar/laborki_git/cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sitar/laborki_git/cmake/CMakeFiles /home/sitar/laborki_git/cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sitar/laborki_git/cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GotowyProgram

# Build rule for target.
GotowyProgram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GotowyProgram
.PHONY : GotowyProgram

# fast build rule for target.
GotowyProgram/fast:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/build
.PHONY : GotowyProgram/fast

src/hw_hello.o: src/hw_hello.c.o

.PHONY : src/hw_hello.o

# target to build an object file
src/hw_hello.c.o:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_hello.c.o
.PHONY : src/hw_hello.c.o

src/hw_hello.i: src/hw_hello.c.i

.PHONY : src/hw_hello.i

# target to preprocess a source file
src/hw_hello.c.i:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_hello.c.i
.PHONY : src/hw_hello.c.i

src/hw_hello.s: src/hw_hello.c.s

.PHONY : src/hw_hello.s

# target to generate assembly for a file
src/hw_hello.c.s:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_hello.c.s
.PHONY : src/hw_hello.c.s

src/hw_main.o: src/hw_main.c.o

.PHONY : src/hw_main.o

# target to build an object file
src/hw_main.c.o:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_main.c.o
.PHONY : src/hw_main.c.o

src/hw_main.i: src/hw_main.c.i

.PHONY : src/hw_main.i

# target to preprocess a source file
src/hw_main.c.i:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_main.c.i
.PHONY : src/hw_main.c.i

src/hw_main.s: src/hw_main.c.s

.PHONY : src/hw_main.s

# target to generate assembly for a file
src/hw_main.c.s:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_main.c.s
.PHONY : src/hw_main.c.s

src/hw_power.o: src/hw_power.c.o

.PHONY : src/hw_power.o

# target to build an object file
src/hw_power.c.o:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_power.c.o
.PHONY : src/hw_power.c.o

src/hw_power.i: src/hw_power.c.i

.PHONY : src/hw_power.i

# target to preprocess a source file
src/hw_power.c.i:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_power.c.i
.PHONY : src/hw_power.c.i

src/hw_power.s: src/hw_power.c.s

.PHONY : src/hw_power.s

# target to generate assembly for a file
src/hw_power.c.s:
	$(MAKE) -f CMakeFiles/GotowyProgram.dir/build.make CMakeFiles/GotowyProgram.dir/src/hw_power.c.s
.PHONY : src/hw_power.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... GotowyProgram"
	@echo "... edit_cache"
	@echo "... src/hw_hello.o"
	@echo "... src/hw_hello.i"
	@echo "... src/hw_hello.s"
	@echo "... src/hw_main.o"
	@echo "... src/hw_main.i"
	@echo "... src/hw_main.s"
	@echo "... src/hw_power.o"
	@echo "... src/hw_power.i"
	@echo "... src/hw_power.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

